import * as icons from "../base";

export enum Variant {
  About = "about",
  ArrowLeft = "arrow-left",
  ArrowRight = "arrow-right",
  AtMentions = "at-mentions",
  AttachFile = "attach-file",
  Back = "back",
  BellNoNotification = "bell-no-notification",
  BellNotification = "bell-notification",
  Bold = "bold",
  BulletList = "bulleted-list",
  Camera = "camera",
  Checkmark = "checkmark",
  CircleCheck = "circle-check",
  Close = "close",
  Code = "code",
  CollapseLesson = "collapse-lesson",
  CollapseList = "collapse-list",
  Diamond = "diamond",
  Discussion = "discussion",
  Download = "download",
  EmojiPicker = "emoji-picker",
  ExpandCard = "expand-card",
  Expand = "expand",
  ExpandLesson = "expand-lesson",
  ExpandList = "expand-list",
  EyeClosed = "eye-closed",
  EyeOpen = "eye-open",
  Flag = "flag",
  FlipCamera = "flip-camera",
  FullscreenExit = "fullscreen-exit",
  Fullscreen = "fullscreen",
  HeartEmpty = "heart-empty",
  HeartFilled = "heart-filled",
  Home = "home",
  Hourglass = "hourglass",
  Image = "image",
  Images = "images",
  Italics = "italics",
  Link = "link",
  Lock = "lock",
  Messaging = "messaging",
  MoreDropdown = "more-dropdown",
  More = "more",
  OrderedList = "ordered-list",
  Peers = "peers",
  Pencil = "pencil",
  PersonOutline = "person-outline",
  PitchTrainer = "pitch-trainer",
  Plus = "plus",
  Posts = "posts",
  Question = "question",
  RecordAudio = "record-audio",
  RecordVideo = "record-video",
  Reply = "reply",
  RightChevron = "right-chevron",
  Save = "save",
  Search = "search",
  Share = "share",
  Sidebar = "sidebar",
  Spark = "spark",
  Studio = "studio",
  ThreeDotHorizontal = "three-dot-horizontal",
  Underline = "underline",
  UploadAudio = "upload-audio",
  UploadVideo = "upload-video",
  Warning = "warning",
}

export const VariantIcons = {
  [Variant.About]: icons.AboutIcon,
  [Variant.ArrowLeft]: icons.ArrowLeftIcon,
  [Variant.ArrowRight]: icons.ArrowRightIcon,
  [Variant.AtMentions]: icons.AtMentionsIcon,
  [Variant.AttachFile]: icons.AttachFileIcon,
  [Variant.Back]: icons.BackIcon,
  [Variant.BellNoNotification]: icons.BellNoNotificationIcon,
  [Variant.BellNotification]: icons.BellNotificationIcon,
  [Variant.Bold]: icons.BoldIcon,
  [Variant.BulletList]: icons.BulletListIcon,
  [Variant.Camera]: icons.CameraIcon,
  [Variant.Checkmark]: icons.CheckmarkIcon,
  [Variant.CircleCheck]: icons.CircleCheckIcon,
  [Variant.Close]: icons.CloseIcon,
  [Variant.Code]: icons.CodeIcon,
  [Variant.CollapseLesson]: icons.CollapseLessonIcon,
  [Variant.CollapseList]: icons.CollapseListIcon,
  [Variant.Diamond]: icons.DiamondIcon,
  [Variant.Discussion]: icons.DiscussionIcon,
  [Variant.Download]: icons.DownloadIcon,
  [Variant.EmojiPicker]: icons.EmojiPickerIcon,
  [Variant.ExpandCard]: icons.ExpandCardIcon,
  [Variant.Expand]: icons.ExpandIcon,
  [Variant.ExpandLesson]: icons.ExpandLessonIcon,
  [Variant.ExpandList]: icons.ExpandListIcon,
  [Variant.EyeClosed]: icons.EyeClosedIcon,
  [Variant.EyeOpen]: icons.EyeOpenIcon,
  [Variant.Flag]: icons.FlagIcon,
  [Variant.FlipCamera]: icons.FlipCameraIcon,
  [Variant.FullscreenExit]: icons.FullscreenExitIcon,
  [Variant.Fullscreen]: icons.FullscreenIcon,
  [Variant.HeartEmpty]: icons.HeartEmptyIcon,
  [Variant.HeartFilled]: icons.HeartFilledIcon,
  [Variant.Home]: icons.HomeIcon,
  [Variant.Hourglass]: icons.HourglassIcon,
  [Variant.Image]: icons.ImageIcon,
  [Variant.Images]: icons.ImagesIcon,
  [Variant.Italics]: icons.ItalicsIcon,
  [Variant.Link]: icons.LinkIcon,
  [Variant.Lock]: icons.LockIcon,
  [Variant.Messaging]: icons.MessagingIcon,
  [Variant.MoreDropdown]: icons.MoreDropdownIcon,
  [Variant.More]: icons.MoreIcon,
  [Variant.OrderedList]: icons.OrderedListIcon,
  [Variant.Peers]: icons.PeersIcon,
  [Variant.Pencil]: icons.PencilIcon,
  [Variant.PersonOutline]: icons.PersonOutlineIcon,
  [Variant.PitchTrainer]: icons.PitchTrainerIcon,
  [Variant.Plus]: icons.PlusIcon,
  [Variant.Posts]: icons.PostsIcon,
  [Variant.Question]: icons.QuestionIcon,
  [Variant.RecordAudio]: icons.RecordAudioIcon,
  [Variant.RecordVideo]: icons.RecordVideoIcon,
  [Variant.Reply]: icons.ReplyIcon,
  [Variant.RightChevron]: icons.RightChevronIcon,
  [Variant.Save]: icons.SaveIcon,
  [Variant.Search]: icons.SearchIcon,
  [Variant.Share]: icons.ShareIcon,
  [Variant.Sidebar]: icons.SidebarIcon,
  [Variant.Spark]: icons.SparkIcon,
  [Variant.Studio]: icons.StudioIcon,
  [Variant.ThreeDotHorizontal]: icons.ThreeDotsHorizontalGray,
  [Variant.Underline]: icons.UnderlineIcon,
  [Variant.UploadAudio]: icons.UploadAudioIcon,
  [Variant.UploadVideo]: icons.UploadVideoIcon,
  [Variant.Warning]: icons.WarningIcon,
};
