import * as icons from "../base";

export enum IconVariant {
  About = "about",
  ArrowLeft = "arrow-left",
  ArrowRight = "arrow-right",
  AtMentions = "at-mentions",
  AttachFile = "attach-file",
  Back = "back",
  BellNoNotification = "bell-no-notification",
  BellNotification = "bell-notification",
  BellUniversalNotification = "bell-universal-notification",
  Bold = "bold",
  BulletList = "bulleted-list",
  Camera = "camera",
  Checkmark = "checkmark",
  CircleCheck = "circle-check",
  Close = "close",
  Code = "code",
  CollapseList = "collapse-list",
  Diamond = "diamond",
  Discussion = "discussion",
  DoubleChevron = "double-chevron-icon",
  Download = "download",
  EmojiPicker = "emoji-picker",
  ExpandCard = "expand-card",
  Expand = "expand",
  ExpandList = "expand-list",
  EyeClosed = "eye-closed",
  EyeOpen = "eye-open",
  FaceSmile = "face-smile",
  Flag = "flag",
  FlipCamera = "flip-camera",
  FullscreenExit = "fullscreen-exit",
  Fullscreen = "fullscreen",
  Hamburger = "hamburger",
  HeartEmpty = "heart-empty",
  HeartFilled = "heart-filled",
  Home = "home",
  Hourglass = "hourglass",
  Image = "image",
  Images = "images",
  Italics = "italics",
  Link = "link",
  Lock = "lock",
  Messaging = "messaging",
  Minus = "minus",
  MoreDropdown = "more-dropdown",
  More = "more",
  OrderedList = "ordered-list",
  Peers = "peers",
  Pencil = "pencil",
  PersonOutline = "person-outline",
  PitchTrainer = "pitch-trainer",
  Plus = "plus",
  Posts = "posts",
  Question = "question",
  RecordAudio = "record-audio",
  RecordVideo = "record-video",
  Reply = "reply",
  RightChevron = "right-chevron",
  Save = "save",
  Search = "search",
  Share = "share",
  Sidebar = "sidebar",
  Spark = "spark",
  Studio = "studio",
  ThreeDotHorizontal = "three-dot-horizontal",
  Underline = "underline",
  UpDown = "up-down",
  UploadAudio = "upload-audio",
  UploadVideo = "upload-video",
  Warning = "warning",
  Delete = "delete",
  Archive = "archive",
  Info = "info",
}

export const VariantIcons = {
  [IconVariant.About]: icons.AboutIcon,
  [IconVariant.ArrowLeft]: icons.ArrowLeftIcon,
  [IconVariant.ArrowRight]: icons.ArrowRightIcon,
  [IconVariant.AtMentions]: icons.AtMentionsIcon,
  [IconVariant.AttachFile]: icons.AttachFileIcon,
  [IconVariant.Back]: icons.BackIcon,
  [IconVariant.BellNoNotification]: icons.BellNoNotificationIcon,
  [IconVariant.BellNotification]: icons.BellNotificationIcon,
  [IconVariant.BellUniversalNotification]: icons.BellUniversalNotification,
  [IconVariant.Bold]: icons.BoldIcon,
  [IconVariant.BulletList]: icons.BulletListIcon,
  [IconVariant.Camera]: icons.CameraIcon,
  [IconVariant.Checkmark]: icons.CheckmarkIcon,
  [IconVariant.CircleCheck]: icons.CircleCheckIcon,
  [IconVariant.Close]: icons.CloseIcon,
  [IconVariant.Code]: icons.CodeIcon,
  [IconVariant.CollapseList]: icons.CollapseListIcon,
  [IconVariant.Diamond]: icons.DiamondIcon,
  [IconVariant.Discussion]: icons.DiscussionIcon,
  [IconVariant.DoubleChevron]: icons.DoubleChevronIcon,
  [IconVariant.Download]: icons.DownloadIcon,
  [IconVariant.EmojiPicker]: icons.EmojiPickerIcon,
  [IconVariant.ExpandCard]: icons.ExpandCardIcon,
  [IconVariant.Expand]: icons.ExpandIcon,
  [IconVariant.ExpandList]: icons.ExpandListIcon,
  [IconVariant.EyeClosed]: icons.EyeClosedIcon,
  [IconVariant.EyeOpen]: icons.EyeOpenIcon,
  [IconVariant.FaceSmile]: icons.FaceSmileIcon,
  [IconVariant.Flag]: icons.FlagIcon,
  [IconVariant.FlipCamera]: icons.FlipCameraIcon,
  [IconVariant.FullscreenExit]: icons.FullscreenExitIcon,
  [IconVariant.Fullscreen]: icons.FullscreenIcon,
  [IconVariant.Hamburger]: icons.HamburgerIcon,
  [IconVariant.HeartEmpty]: icons.HeartEmptyIcon,
  [IconVariant.HeartFilled]: icons.HeartFilledIcon,
  [IconVariant.Home]: icons.HomeIcon,
  [IconVariant.Hourglass]: icons.HourglassIcon,
  [IconVariant.Image]: icons.ImageIcon,
  [IconVariant.Images]: icons.ImagesIcon,
  [IconVariant.Italics]: icons.ItalicsIcon,
  [IconVariant.Link]: icons.LinkIcon,
  [IconVariant.Lock]: icons.LockIcon,
  [IconVariant.Messaging]: icons.MessagingIcon,
  [IconVariant.Minus]: icons.MinusIcon,
  [IconVariant.MoreDropdown]: icons.MoreDropdownIcon,
  [IconVariant.More]: icons.MoreIcon,
  [IconVariant.OrderedList]: icons.OrderedListIcon,
  [IconVariant.Peers]: icons.PeersIcon,
  [IconVariant.Pencil]: icons.PencilIcon,
  [IconVariant.PersonOutline]: icons.PersonOutlineIcon,
  [IconVariant.PitchTrainer]: icons.PitchTrainerIcon,
  [IconVariant.Plus]: icons.PlusIcon,
  [IconVariant.Posts]: icons.PostsIcon,
  [IconVariant.Question]: icons.QuestionIcon,
  [IconVariant.RecordAudio]: icons.RecordAudioIcon,
  [IconVariant.RecordVideo]: icons.RecordVideoIcon,
  [IconVariant.Reply]: icons.ReplyIcon,
  [IconVariant.RightChevron]: icons.RightChevronIcon,
  [IconVariant.Save]: icons.SaveIcon,
  [IconVariant.Search]: icons.SearchIcon,
  [IconVariant.Share]: icons.ShareIcon,
  [IconVariant.Sidebar]: icons.SidebarIcon,
  [IconVariant.Spark]: icons.SparkIcon,
  [IconVariant.Studio]: icons.StudioIcon,
  [IconVariant.ThreeDotHorizontal]: icons.ThreeDotsHorizontalGray,
  [IconVariant.Underline]: icons.UnderlineIcon,
  [IconVariant.UpDown]: icons.UpDownIcon,
  [IconVariant.UploadAudio]: icons.UploadAudioIcon,
  [IconVariant.UploadVideo]: icons.UploadVideoIcon,
  [IconVariant.Warning]: icons.WarningIcon,
  [IconVariant.Delete]: icons.DeleteIcon,
  [IconVariant.Archive]: icons.ArchiveIcon,
  [IconVariant.Info]: icons.InfoIcon,
};
